config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :trains do
      resources :carriages, only: [:create, :show]
    end

    resources :railway_stations, :routes
  end

  resources :tickets, except: [:edit, :update, :show]
  resource :search, only: [:show, :new, :edit]
  root "searches#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :stations_routes, class_name: "StationsRoute", foreign_key: "railway_station_id"
  has_many :routes, through: :stations_routes
  validates :title, presence: true, uniqueness: { case_sensitive: true }
  
  
end

app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  # GET /railway_stations
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations
  def create
    @railway_station = RailwayStation.new(railway_station_params)
    if @railway_station.save
      redirect_to [:admin, @railway_station], notice: 'Railway station was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /railway_stations/1
  def update
    if @railway_station.update(railway_station_params)
      redirect_to [:admin, @railway_station], notice: 'Railway station was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /railway_stations/1
  def destroy
    @railway_station.destroy
    redirect_to admin_railway_stations_url, notice: 'Railway station was successfully destroyed.'
  end

  private
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  # GET /railway_stations
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations
  def create
    @railway_station = RailwayStation.new(railway_station_params)
    if @railway_station.save
      redirect_to @railway_station, notice: 'Railway station was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /railway_stations/1
  def update
    if @railway_station.update(railway_station_params)
      redirect_to @railway_station, notice: 'Railway station was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /railway_stations/1
  def destroy
    @railway_station.destroy
    redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.'
  end

  private
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/admin/railway_stations/_form.html.erb
<%= form_with(model: [:admin, railway_station], local: true) do |form| %>
  <% if railway_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(railway_station.errors.count, "error") %> prohibited this railway_station from being saved:</h2>

      <ul>
      <% railway_station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
      <%= form.label :title%>
      <%= form.text_field :title, class: "form-control"%>
  </div><br/>
  <div class="actions">
    <%= form.submit "KK", class: "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" %>
  </div>
<% end %>

app/views/admin/railway_stations/edit.html.erb
<div class="col-md-4">
<h1><%= t('editing_station')%></h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to t('show'), [:admin, @railway_station] %> |
<%= link_to t('back'), admin_railway_stations_path %>
</div>

app/views/admin/railway_stations/index.html.erb
<h1><%= t('stations')%></h1>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @railway_stations.each do |railway_station| %>
      <tr>
        <td><%= railway_station.title %></td>
        <td><%= link_to t('show'), admin_railway_station_path(railway_station) %></td>
        <td><%= link_to t('edit'), edit_admin_railway_station_path(railway_station) %></td>
        <td><%= link_to t('destroy'), admin_railway_station_path(railway_station), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new_station'), new_admin_railway_station_path %><br/>

app/views/admin/railway_stations/new.html.erb
<div class="col-md-4">
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to t('back'), admin_railway_stations_path %>
</div>

app/views/admin/railway_stations/show.html.erb
<h2><%= @railway_station.title %></h2>

<%= link_to t('edit'), edit_admin_railway_station_path(@railway_station) %> |
<%= link_to t('back'), admin_railway_stations_path %>