config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :trains do
      resources :carriages, only: [:create, :show]
    end

    resources :railway_stations, :routes
  end

  resources :tickets, except: [:edit, :update, :show]
  resource :search, only: [:show, :new, :edit]
  root "searches#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :stations_routes, class_name: "StationsRoute", foreign_key: "route_id"
  has_many :railway_stations, through: :stations_routes, dependent: :destroy
  has_many :trains, class_name: "Train", foreign_key: "route_id"

  validates :name, presence: true, uniqueness: true
  # validate :stations_count

  private

  def self.search_routes(from, to)
    routes = []
    result = []
    to.routes.each do |route|
      station = route.railway_stations.where(id: from.id).first
      position_from = route.stations_routes.where(railway_station_id: from.id).first.try(:position)
      position_to = route.stations_routes.where(railway_station_id: to.id).first.try(:position)
      if position_from.present? && position_to.present?
        if position_from < position_to && !station.nil?
          routes << station.routes.find_by(id: route.id)
        end
      end
    end
    routes.each do |route|
      result << route if route.trains.present?
    end
    return result
  end

  def self.set_times(route, times)
    times.each do |k, v|
      if v.length > 0
        time = route.stations_routes.where(railway_station_id: k).first
        time.time = v.to_s
        time.save
      end
    end
  end

  # def stations_count
  #   errors.add(:base, "Route should contain at least 2 stations #{railway_stations.inspect}") if railway_stations.size < 2
  # end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_action :set_stations, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
    @stations = @route.railway_stations.order(:position)
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(params_route)
    @railway_stations = RailwayStation.find(params[:model_ids]) if params.has_key?(:model_ids)
      if @route.save
        @route.railway_stations = @railway_stations
        @times = params[:times]
        Route.set_times(@route, @times)
        redirect_to admin_route_path(@route), alert: "After create need to edit the route's positions. "
      else
        render :new
      end
  end

  def edit
  end

  def update
    @railway_stations = RailwayStation.find(params[:model_ids])
    if @route.update(params_route)
      @route.railway_stations = @railway_stations
      @route.save
      @times = params[:times]
      Route.set_times(@route, @times)
      redirect_to admin_route_path(@route)
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end


  private

  def params_route
    params.require(:route).permit(:name, :time, model_ids: [])
  end

  def set_route
    @route = Route.find(params[:id])
  end

  def set_stations
    @sr = @route.stations_routes.order(:position).all
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_action :set_stations, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
    @stations = @route.railway_stations.order(:position)
  end

  def new
    @route = Route.new
  end

  def create
    @railway_stations = RailwayStation.find(params[:model_ids])
    @route = Route.new(params_route)
      if @route.save
        @route.railway_stations = @railway_stations
        @times = params[:times]
        Route.set_times(@route, @times)
        redirect_to @route
      else
        render :new
      end
  end

  def edit
  end

  def update
    @railway_stations = RailwayStation.find(params[:model_ids])
    if @route.update(params_route)
      @route.railway_stations = @railway_stations
      @times = params[:times]
      Route.set_times(@route, @times)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end


  private

  def params_route
    params.require(:route).permit(:name, :time)
  end

  def set_route
    @route = Route.find(params[:id])
  end

  def set_stations
    @sr = @route.stations_routes.order(:position).all
  end
end

app/views/admin/routes/_form.html.erb
<%= form_with(model: [:admin, route], local: true) do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
  <div class="form-group">
    <%= label_tag t('routes_name') %>
    <%= form.text_field :name, class: "form-control"%>
  </div>
  <div class="field">
  <div class="row">
    <div class="col-sm-3"><b><%= t('station') %></b></div>
    <div class="col-md-3 ml-auto"><b><%= t('time') %></b></div>
  </div>
    <% RailwayStation.all.each do |model|%>
      <div class="row form-group">
        <%= check_box_tag('model_ids[]', model.id, checked = route.railway_stations.include?(model)) %>
        <%= label_tag model.title%>
        <div class=" ml-auto" ><%= text_field_tag "times[#{model.id}]", nil, value: route.stations_routes.find_by(railway_station_id: model.id).try(:time), class: "form-control" %></div>
      </div>
    <%end%>
  </div>
    <%= form.submit :OK, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/routes/edit.html.erb
<div class="row">
<div class="col-sm-6">
<h1><%= t('editing_route') %> "<%= @route.name %>"</h1>
<%= render 'form', route: @route %>
</div>
<div class="col-sm-6">
<b><%= t('route') %>:</b>
<ul id="stations" class="list-group sortable">
  <% @sr.each_with_sortable_id do |sr, sortable_id| %>
      <%= link_to sr.railway_station.title, [:admin, sr.railway_station], class: "list-group-item", id: sortable_id %>
  <% end %>
</ul>
</div>
</div>
<%= link_to t('show'), admin_route_path(@route) %>|
<%= link_to t('back'), admin_routes_path %>

app/views/admin/routes/index.html.erb
<h1><%= t('routes') %></h1>

<table>
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= link_to t('show'), admin_route_path(route) %></td>
        <td><%= link_to t('edit'), edit_admin_route_path(route) %></td>
        <td><%= link_to t('destroy'), admin_route_path(route), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new_route'), new_admin_route_path %><br/>

app/views/admin/routes/new.html.erb
<div class="col-md-6">
<h1><%= t('new_route') %></h1>

<%= render 'form', route: @route %>

<%= link_to t('back'), admin_routes_path %>
</div>

app/views/admin/routes/show.html.erb
<h2><%= @route.name %></h2>
  <p><%= t('trains_list') %>: </p>
  <% @route.trains.each do |train|%>
  <p><%= link_to train.number, admin_train_path(train) %></p>
  <% end %>
  <hr/>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p><b><%= t('route') %>:</b></p>
    <ul class="list-group">
      <% @stations.each do |station| %>
          <%= link_to admin_railway_station_path(station), class: "list-group-item" do %>
          <span><%= station.title %></span>
          <span style="float: right;"><%= @route.stations_routes.find_by(railway_station_id: station.id).time %></span>
          <% end %>
      <% end %>
    </ul>
  </div>
</div>
<%= link_to t('edit'), edit_admin_route_path(@route)%>
<%= link_to t('back'), admin_routes_path %>