config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :trains do
      resources :carriages, only: [:create, :show]
    end

    resources :railway_stations, :routes
  end

  resources :tickets, except: [:edit, :update, :show]
  resource :search, only: [:show, :new, :edit]
  root "searches#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :route, optional: true
  has_many :tickets
  has_many :carriages

  validates :number, presence: true, uniqueness: true
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_train, only: [:show, :edit, :update, :destroy]
  before_action :train_info, only: [:show, :edit]

  # GET /trains
  def index
    @trains = Train.all
  end

  # GET /trains/1
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to [:admin, @train], notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    if @train.update(train_params)
      redirect_to [:admin, @train], notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trains/1
  def destroy
    @train.destroy
    redirect_to admin_trains_url, notice: 'Train was successfully destroyed.'
  end

  private
    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:number, :route_id)
    end

    def train_info
      @comfort_carriages = @train.carriages.where(type: "ComfortCarriage")
      @economy_carriages = @train.carriages.where(type: "EconomyCarriage")
      @comfort_seats = @comfort_carriages.pluck(:seats).sum
      @economy_seats = @economy_carriages.pluck(:seats).sum
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]
  before_action :train_info, only: [:show, :edit]

  # GET /trains
  def index
    @trains = Train.all
  end

  # GET /trains/1
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to @train, notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    if @train.update(train_params)
      redirect_to @train, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trains/1
  def destroy
    @train.destroy
    redirect_to trains_url, notice: 'Train was successfully destroyed.'
  end

  private
    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:number, :route_id)
    end

    def train_info
      @comfort_carriages = @train.carriages.where(type: "ComfortCarriage")
      @economy_carriages = @train.carriages.where(type: "EconomyCarriage")
      @comfort_seats = @comfort_carriages.pluck(:seats).sum
      @economy_seats = @economy_carriages.pluck(:seats).sum
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_with(model: [:admin, train], local: true) do |form| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="row">
    <div class="col-md-3">
      <%= form.label :number%>
      <%= form.number_field :number, class: "form-control"%>
    </div>
    <% @routes = Route.all %>
    <div class="col-md-4">
      <%= form.label t('route') %>
      <%= form.select 'route_id', options_from_collection_for_select(@routes, 'id', 'name'), {:include_blank => true } %>
    </div>
    <%= form.submit :Ok, class: "btn btn-sm btn-success" %>
  </div>
<% end %>

app/views/admin/trains/edit.html.erb
<h1><%= t('edit_train')%></h1>

<%= render 'form', train: @train %>

<%= form_for [:admin, @train, @train.carriages.build] do |f|%>
<%= f.radio_button(:type, 'ComfortCarriage') %>
<%= f.label t('comfort') %>
<%= f.radio_button(:type, "EconomyCarriage") %>
<%= f.label t('economy') %>
<%= f.submit %>
<%end%>

<%= link_to t('show'), [:admin, @train] %> |
<%= link_to t('back'), admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1><%= t('trains')%></h1>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= link_to t('show'), [:admin, train] %></td>
        <td><%= link_to t('edit'), edit_admin_train_path(train) %></td>
        <td><%= link_to t('destroy'), [:admin, train], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new_train'), new_admin_train_path %><br/>

app/views/admin/trains/new.html.erb
<h1><%= t('new_train') %></h1>

<%= render 'form', train: @train %>

<%= link_to t('back'), admin_trains_path %>

app/views/admin/trains/show.html.erb
<p><%= t('train_number') %>: <%= @train.number %></p>
<p><%= t('route') %>: 
<% unless @train.route.nil? %>
  <%= link_to @train.route.name, [:admin, @train.route] %>
<% else %>
  Маршрут не назначен!
<% end %></p></hr>
<p><%= t('number_of_carriages') %>: <%= @train.carriages.length %></p>
<p><%= t('comfort') %>: <%= @comfort_carriages.length%> <%= t('number_of_seats') %>: <%= @comfort_seats%></p>
<p><%= t('economy') %>: <%= @economy_carriages.length%> <%= t('number_of_seats') %>: <%= @economy_seats%></p><hr/>
<div class="card-columns">
  <% @train.carriages.each do |carriage| %>
    <%= link_to admin_train_carriage_path(@train, carriage) do %>
      <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
        <div class="card-header"><%= t('carriage') %> № <%= carriage.number%>.</div>
        <div class="card-body">
          <h5 class="card-title"><%= t('carriage_type') %>: <%= carriage.type%>.</h5>
          <p class="card-text"><%= t('number_of_seats') %>: <%= carriage.seats%>.</p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to t('edit'), edit_admin_train_path(@train) %> |
<%= link_to t('back'), admin_trains_path %>