config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :trains do
      resources :carriages, only: [:create, :show]
    end

    resources :railway_stations, :routes
  end

  resources :tickets, except: [:edit, :update, :show]
  resource :search, only: [:show, :new, :edit]
  root "searches#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%=link_to search_path do %>
      <img class="nav-brand" src="/tutu1.png" width="64" height="32" alt="">
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <% if user_signed_in? && current_user.admin? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= admin_trains_path %>"><%= t('trains') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= admin_routes_path %>"><%= t('routes') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= admin_railway_stations_path %>"><%= t('stations') %></a>
        </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="<%= search_path %>"><%= t('search_title') %></a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% unless signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_session_path %>"><%= t('login') %></a>
        </li>
        <% else %>
        <li class="nav-item">
          <a class="nav-link" href="<%= tickets_path %>"><%= t('my_tickets')%></a>
        </li>
        <li class="nav-item">
          <%= link_to t('quit'), destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class="container">
    <% if notice %>
    <p class="notice alert alert-success" id="notice"><%= notice %></p>
    <% elsif alert %>
    <p class="alert alert-danger" id="notice"><%= alert %></p>
    <% end %>
    <%= yield %>
    </div>
    <div id="footer">Учебное приложение по Ruby on Rails. Шамгулов Марс, 2019 год.</div>
  </%=>
</html>